name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        name: "Deploy to VPS"
        runs-on: ubuntu-18.04
        steps:
            - name: Configure SSH
              run: |
                mkdir -p ~/.ssh/
                echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
                chmod 600 ~/.ssh/deploy-key.pem
                cat >> ~/.ssh/config <<END
                Host my-vps
                    HostName $SSH_IP
                    User $SSH_USER
                    IdentityFile ~/.ssh/deploy-key.pem
                END
              env:
                SSH_IP: ${{ secrets.SSH_IP }}
                SSH_USER: ${{ secrets.SSH_USER }}
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: Deploy
              run: ssh my-vps "cd ${{ secrets.PROJECT_ROOT }} && pwd"